# Generated by Django 5.2.9 on 2026-05-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='C:\\Users\\ESTUDIANTE\\Desktop\\proyecto_sena\\project\\static\\img\\user.jpg', upload_to='users/imagenes'),
        ),
    ]
