# Generated by Django 5.2.9 on 2026-03-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(default='img/yokse.png', upload_to='imagenes/'),
        ),
    ]
