# Generated by Django 5.2.9 on 2026-03-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(blank=True, default='img/yokse.png', null=True, upload_to='imagenes/'),
        ),
    ]
