# Generated by Django 5.2.9 on 2026-05-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
