# Generated by Django 4.2 on 2026-05-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='/users/imagenes/user.jpg', upload_to='users/imagenes'),
        ),
    ]
