# Generated by Django 4.2 on 2026-05-19 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='imagen',
            field=models.ImageField(default='/users/imagenes/user.jpg', upload_to='imagenes/'),
        ),
    ]
