# Generated by Django 5.2.9 on 2026-03-23 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic_section',
            name='posts',
            field=models.ManyToManyField(blank=True, to='catalog.post'),
        ),
        migrations.AddField(
            model_name='topics_group',
            name='posts',
            field=models.ManyToManyField(blank=True, to='catalog.post'),
        ),
        migrations.AddField(
            model_name='topics_group',
            name='users_joined',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic_section',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='catalog.topics_group'),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='catalog.topics_group'),
        ),
    ]
