# Generated by Django 4.2 on 2026-05-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_postimagen_imagen_postimagen_post_postvideo_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ia_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
