# Generated by Django 4.2 on 2026-05-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_group_post_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group_id',
            new_name='group',
        ),
    ]
