# Generated by Django 4.2 on 2026-05-29 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_group_post_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group_id',
        ),
    ]
