# Generated by Django 4.2 on 2026-05-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_post_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='groups',
            new_name='group',
        ),
    ]
