# Generated by Django 4.2 on 2026-05-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_post_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, db_column='group_id', default=14, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='catalog.topics_group'),
        ),
    ]
