# Generated by Django 4.2 on 2026-05-29 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, default=14, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='catalog.topics_group'),
        ),
    ]
