# Generated by Django 4.2 on 2026-05-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_post_group_remove_post_ia_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='catalog.topics_group'),
        ),
        migrations.AddField(
            model_name='post',
            name='ia_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
