# Generated by Django 4.2 on 2026-07-04 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0018_post_group_post_ia_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics_group',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topics_group',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topics_group',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscribed_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
