# Generated by Django 4.2 on 2026-07-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_topics_group_dislikes_topics_group_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics_group',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='group_posts', to='catalog.post'),
        ),
    ]
