# Generated by Django 4.2 on 2026-07-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_topics_group_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topics_group',
            name='posts',
        ),
    ]
